In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/bipulshahi/Dataset/refs/heads/main/Advertising.csv',
                 index_col=0)
df.head()

      TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [ ]:
X = df[['TV', 'radio' ,	'newspaper']]
y = df['sales']

In [ ]:
#Yh = w0 + w1X1 + w2X2 + w3X3

w0 = 1
w1 = 1
w2 = 1
w3 = 1

Yh = w0 + w1*X.TV + w2*X.radio + w3*X.newspaper          #feed forward process
print(Yh)

1      338.1
2      129.9
3      133.4
4      252.3
5      251.0
       ...
196     56.7
197    108.2
198    193.7
199    392.8
200    250.4
Length: 200, dtype: float64

In [ ]:
error = ((y - Yh)**2).mean()
print(error)

43075.487700000005

In [ ]:
#Cacluate gradient

w0 = 1
w1 = 1
w2 = 1
w3 = 1

for i in range(0,1000):
  Yh = w0 + w1*X.TV + w2*X.radio + w3*X.newspaper

  dew0 = -2*((y - Yh)).mean()
  dew1 = -2*((y - Yh)*X.TV).mean()
  dew2 = -2*((y - Yh)*X.radio).mean()
  dew3 = -2*((y - Yh)*X.newspaper).mean()

  lr = 1e-5

  w0 = w0 - lr * dew0
  w1 = w1 - lr * dew1
  w2 = w2 - lr * dew2
  w3 = w3 - lr * dew3

  error = ((y - Yh)**2).mean()
  print(i,error)

0 43075.487700000005
1 7491.763209516504
2 1855.6388700406212
3 945.3545789556888
4 781.3784736126752
5 735.7958666336327
6 709.513681701826
7 686.8773932371062
8 665.3980954505818
9 644.6647612598013
10 624.5947904593736
11 605.1579615548646
12 586.3328590296188
13 568.0999813347377
14 550.4406369320286
15 533.3367541016861
16 516.7708354290318
17 500.7259356074313
18 485.18564339325474
19 470.134064674236
20 455.5558061573512
21 441.4359595842996
22 427.76008644654377
23 414.51420318236063
24 401.6847668404317
25 389.25866119522374
26 377.22318329991737
27 365.5660304630916
28 354.2752876358126
29 343.3394151961925
30 332.7472371188915
31 322.48792951743513
32 312.55100954759604
33 302.92632466046217
34 293.6040421941734
35 284.5746392936515
36 275.82889314798905
37 267.35787153548745
38 259.15292366664653
39 251.20567131571886
40 243.50800023173426
41 236.05205182018727
42 228.83021508685837
43 221.83511883550852
44 215.0596241114464
45 208.49681688322008
46 202.14000095492972
47 195.9826911018925
48 190.0186064226226
49 184.24166390030857
50 178.64597216718622
51 173.22582546541423
52 167.97569779825807
53 162.89023726558742
54 157.96426057787633
55 153.19274774308337
56 148.570836920962
57 144.09381943952516
58 139.7571349685558
59 135.55636684521136
60 131.48723754693222
61 127.54560430701007
62 123.72745486832162
63 120.02890337087325
64 116.44618636893992
65 112.9756589737142
66 109.61379111751062
67 106.35716393569425
68 103.20246626262433
69 100.14649123801927
70 97.18613302026365
71 94.31838360328754
72 91.54032973375323
73 88.84914992538953
74 86.2421115674116
75 83.71656812406123
76 81.26995642239679
77 78.89979402555103
78 76.60367668876395
79 74.37927589558204
80 72.22433647169764
81 70.13667427398164
82 68.11417395234015
83 66.15478678210009
84 64.2565285647012
85 62.417477594541886
86 60.63577268989415
87 58.9096112858688
88 57.23724758747532
89 55.61699078088281
90 54.04720330104764
91 52.52629915393205
92 51.05274229159281
93 49.625045038474155
94 48.24176656729141
95 46.901511422942406
96 45.60292809293338
97 44.3447076228533
98 43.125582275477335
99 41.94432423212425
100 40.79974433493649
101 39.69069086879313
102 38.61604838160682
103 37.57473654179528
104 36.56570903175562
105 35.58795247620705
106 34.64048540430333
107 33.72235724445044
108 32.83264735079921
109 31.97046406041445
110 31.134943780154035
111 30.325250102321665
112 29.540572948186608
113 28.780127738492084
114 28.043154590102084
115 27.328917537962653
116 26.636703781580145
117 25.965822955243652
118 25.31560642124353
119 24.685406585361225
120 24.07459623392869
121 23.482567891777563
122 22.908733200419857
123 22.352522315822718
124 21.813383325159556
125 21.290781681939837
126 20.784199658938135
127 20.293135818361684
128 19.817104498713185
129 19.355635317822657
130 18.908272691538983
131 18.47457536758752
132 18.054115974115888
133 17.646480582465138
134 17.25126828371798
135 16.868090778589877
136 16.496571980242656
137 16.136347629613283
138 15.787064922863532
139 15.44838215056851
140 15.11996834827416
141 14.801502958065498
142 14.492675500798514
143 14.193185258659867
144 13.902740967728718
145 13.621060520225738
146 13.347870676143788
147 13.082906783964852
148 12.825912510176718
149 12.576639577312273
150 12.334847510242689
151 12.100303390464497
152 11.87278161812866
153 11.652063681567595
154 11.437937934083948
155 11.230199377772252
156 11.028649454151841
157 10.833095841396435
158 10.643352257952456
159 10.4592382723448
160 10.28057911897507
161 10.107205519723438
162 9.938953511171281
163 9.775664277267403
164 9.617183987266383
165 9.463363638772885
166 9.314058905731008
167 9.169129991202896
168 9.028441484785665
169 8.891862224520478
170 8.759265163152252
171 8.63052723860285
172 8.505529248525052
173 8.384155728808633
174 8.2662948359141
175 8.151838232913384
176 8.040680979120776
177 7.932721423200876
178 7.827861099644074
179 7.726004628503372
180 7.627059618289865
181 7.5309365719272705
182 7.437548795669156
183 7.346812310885505
184 7.258645768628187
185 7.172970366887793
186 7.089709770457019
187 7.008790033318449
188 6.930139523477208
189 6.853688850161453
190 6.779370793316085
191 6.707120235317413
192 6.636874094838781
193 6.568571262799426
194 6.502152540330866
195 6.43756057869728
196 6.374739821108317
197 6.31363644636467
198 6.254198314278701
199 6.1963749128141545
200 6.140117306890837
201 6.085378088801739
202 6.032111330191846
203 5.980272535549403
204 5.929818597161994
205 5.880707751491261
206 5.832899536921577
207 5.786354752839377
208 5.7410354200012375
209 5.696904742150056
210 5.653927068840047
211 5.612067859432456
212 5.571293648225073
213 5.531572010679886
214 5.492871530714204
215 5.455161769021792
216 5.41841323239154
217 5.382597343992238
218 5.347686414593052
219 5.313653614690146
220 5.280472947510978
221 5.2481192228685805
222 5.216568031839033
223 5.185795722236223
224 5.155779374858753
225 5.126496780484669
226 5.09792641759046
227 5.0700474307714956
228 5.042839609841824
229 5.016283369591885
230 4.990359730183476
231 4.9650502981618185
232 4.940337248065344
233 4.916203304614341
234 4.892631725460227
235 4.869606284477782
236 4.847111255583263
237 4.825131397061788
238 4.803651936387987
239 4.782658555524355
240 4.762137376682274
241 4.742074948531109
242 4.722458232841287
243 4.703274591547673
244 4.684511774219991
245 4.666157905927504
246 4.648201475485488
247 4.630631324071518
248 4.6134366341998705
249 4.596606919042801
250 4.580132012087757
251 4.564002057119921
252 4.54820749851988
253 4.53273907186646
254 4.517587794835115
255 4.5027449583826
256 4.48820211820885
257 4.473951086487378
258 4.459983923855724
259 4.446292931657758
260 4.432870644429902
261 4.419709822623606
262 4.406803445556612
263 4.394144704585823
264 4.381726996494787
265 4.369543917089028
266 4.357589254992698
267 4.345856985640199
268 4.3343412654566285
269 4.323036426221111
270 4.311936969607256
271 4.301037561895157
272 4.29033302884955
273 4.279818350758853
274 4.269488657630083
275 4.2593392245346955
276 4.2493654671006
277 4.23956293714578
278 4.229927318449005
279 4.220454422653388
280 4.211140185298525
281 4.201980661977238
282 4.192972024612969
283 4.184110557853997
284 4.17539265558088
285 4.166814817523456
286 4.158373645984043
287 4.150065842663444
288 4.141888205586526
289 4.133837626124261
290 4.125911086109163
291 4.11810565504121
292 4.110418487381377
293 4.1028468199300425
294 4.0953879692875805
295 4.088039329394565
296 4.080798369149074
297 4.0736626300986645
298 4.066629724204684
299 4.059697331676608
300 4.052863198874248
301 4.046125136275645
302 4.039481016508622
303 4.0329287724439595
304 4.02646639534829
305 4.02009193309479
306 4.013803488429897
307 4.007599217294241
308 4.001477327196145
309 3.9954360756359586
310 3.9894737685797192
311 3.98358875898051
312 3.977779445346067
313 3.9720442703511445
314 3.966381719493264
315 3.960790319790448
316 3.9552686385196507
317 3.9498152819945824
318 3.944428894381699
319 3.939108156553159
320 3.9338517849755705
321 3.9286585306334256
322 3.9235271779861227
323 3.9184565439574963
324 3.913445476956883
325 3.908492855930681
326 3.903597589443482
327 3.898758614787822
328 3.893974897121668
329 3.8892454286327585
330 3.884569227728954
331 3.8799453382537967
332 3.875372828726453
333 3.870850791605321
334 3.86637834257451
335 3.8619546198525097
336 3.85757878352233
337 3.8532500148824584
338 3.8489675158179533
339 3.8447305081910748
340 3.8405382332507996
341 3.83638995106067
342 3.832284939944367
343 3.828222495948472
344 3.824201932321857
345 3.8202225790112188
346 3.816283782172202
347 3.8123849036956607
348 3.80852532074856
349 3.804704425329078
350 3.800921623835444
351 3.797176336648094
352 3.7934679977247185
353 3.789796054207811
354 3.7861599660443086
355 3.782559205616948
356 3.7789932573869964
357 3.7754616175479567
358 3.771963793689942
359 3.768499304474356
360 3.7650676793185855
361 3.761668458090361
362 3.758301190811503
363 3.754965437370762
364 3.7516607672454465
365 3.7483867592315847
366 3.7451430011823437
367 3.74192908975446
368 3.7387446301623948
369 3.7355892359400285
370 3.7324625287096067
371 3.7293641379577416
372 3.7262937008182364
373 3.7232508618615237
374 3.7202352728905073
375 3.71724659274261
376 3.7142844870978378
377 3.711348628292661
378 3.7084386951395434
379 3.705554372751934
380 3.7026953523745543
381 3.699861331218816
382 3.697052012303216
383 3.694267104298533
384 3.6915063213777
385 3.688769383070195
386 3.686056014120803
387 3.6833659443526345
388 3.680698908534241
389 3.678054646250716
390 3.675432901778663
391 3.6728334239648888
392 3.6702559661087286
393 3.667700285847883
394 3.6651661450476336
395 3.6626533096933906
396 3.660161549786394
397 3.6576906392425332
398 3.6552403557941626
399 3.6528104808947988
400 3.650400799626668
401 3.6480111006109404
402 3.645641175920647
403 3.6432908209961195
404 3.64095983456294
405 3.6386480185522805
406 3.636355178023574
407 3.6340811210894497
408 3.6318256588428466
409 3.629588605286258
410 3.6273697772630205
411 3.6251689943906045
412 3.622986078995831
413 3.620820856051953
414 3.6186731531175576
415 3.61654280027723
416 3.6144296300838956
417 3.6123334775028515
418 3.6102541798573617
419 3.608191576775822
420 3.606145510140428
421 3.6041158240372857
422 3.6021023647079575
423 3.6001049805023526
424 3.598123521832962
425 3.596157841130371
426 3.594207792800022
427 3.592273233180185
428 3.5903540205010995
429 3.5884500148452547
430 3.586561078108768
431 3.584687073963835
432 3.5828278678222114
433 3.580983326799701
434 3.579153319681615
435 3.577337716889181
436 3.575536390446853
437 3.573749213950531
438 3.571976062536616
439 3.570216812851922
440 3.5684713430243784
441 3.566739532634531
442 3.5650212626877953
443 3.5633164155874546
444 3.5616248751083703
445 3.5599465263713825
446 3.558281255818392
447 3.5566289511880926
448 3.5549895014923356
449 3.553362796993108
450 3.5517487291801113
451 3.5501471907489144
452 3.5485580755796695
453 3.546981278716377
454 3.545416696346665
455 3.543864225782103
456 3.542323765438988
457 3.540795214819636
458 3.539278474494123
459 3.5377734460824986
460 3.5362800322374217
461 3.5347981366272427
462 3.5333276639194837
463 3.531868519764737
464 3.530420610780946
465 3.52898384453807
466 3.5275581295431175
467 3.5261433752255322
468 3.5247394919229373
469 3.523346390867207
470 3.5219639841708723
471 3.5205921848138457
472 3.5192309066304484
473 3.5178800642967394
474 3.51653957331815
475 3.5152093500173724
476 3.513889311522562
477 3.5125793757557626
478 3.5112794614216356
479 3.509989487996408
480 3.5087093757170815
481 3.507439045570873
482 3.506178419284895
483 3.504927419316049
484 3.503685968841145
485 3.5024539917472386
486 3.5012314126221553
487 3.500018156745242
488 3.4988141500782834
489 3.4976193192566427
490 3.4964335915805522
491 3.4952568950066065
492 3.4940891581394236
493 3.492930310223475
494 3.4917802811350738
495 3.4906390013745376
496 3.4895064020584954
497 3.4883824149123552
498 3.4872669722629097
499 3.486160007031094
500 3.4850614527248807
501 3.483971243432309
502 3.4828893138146486
503 3.481815599099694
504 3.4807500350751797
505 3.4796925580823213
506 3.478643105009476
507 3.4776016132859193
508 3.476568020875726
509 3.475542266271782
510 3.4745242884898757
511 3.4735140270629143
512 3.4725114220352395
513 3.471516413957033
514 3.4705289438788225
515 3.469548953346086
516 3.4685763843939514
517 3.467611179541968
518 3.4666532817889855
519 3.465702634608103
520 3.464759181941713
521 3.4638228681966194
522 3.462893638239233
523 3.4619714373908472
524 3.4610562114229966
525 3.4601479065528675
526 3.4592464694388037
527 3.4583518471758703
528 3.4574639872914825
529 3.456582837741113
530 3.4557083469040504
531 3.4548404635792362
532 3.4539791369811446
533 3.4531243167357504
534 3.452275952876521
535 3.451433995840502
536 3.4505983964644322
537 3.4497691059809283
538 3.4489460760147197
539 3.4481292585789367
540 3.447318606071448
541 3.446514071271249
542 3.445715607334912
543 3.4449231677930574
544 3.4441367065469035
545 3.4433561778648385
546 3.442581536379056
547 3.441812737082215
548 3.441049735324167
549 3.4402924868087053
550 3.4395409475903644
551 3.438795074071264
552 3.438054822997985
553 3.43732015145849
554 3.4365910168790803
555 3.435867377021393
556 3.435149189979427
557 3.4344364141766177
558 3.4337290083629353
559 3.433026931612028
560 3.43233014331839
561 3.431638603194569
562 3.430952271268402
563 3.4302711078802934
564 3.429595073680507
565 3.428924129626507
566 3.428258236980322
567 3.4275973573059297
568 3.4269414524666932
569 3.426290484622798
570 3.4256444162287467
571 3.4250032100308556
572 3.424366829064794
573 3.42373523665315
574 3.423108396403012
575 3.422486272203587
576 3.4218688282238396
577 3.421256028910155
578 3.4206478389840367
579 3.4200442234398065
580 3.4194451475423544
581 3.4188505768248945
582 3.4182604770867466
583 3.4176748143911495
584 3.4170935550630848
585 3.416516665687128
586 3.4159441131053296
587 3.4153758644150947
588 3.414811886967114
589 3.4142521483632855
590 3.4136966164546845
591 3.4131452593395237
592 3.4125980453611646
593 3.412054943106124
594 3.411515921402114
595 3.4109809493160865
596 3.410449996152318
597 3.4099230314504894
598 3.409400024983802
599 3.4088809467570984
600 3.4083657670050123
601 3.4078544561901243
602 3.407346985001146
603 3.4068433243511094
604 3.406343445375587
605 3.4058473194309133
606 3.4053549180924345
607 3.404866213152766
608 3.4043811766200722
609 3.4038997807163582
610 3.403421997875773
611 3.40294780074294
612 3.4024771621712926
613 3.4020100552214227
614 3.4015464531594533
615 3.40108632945542
616 3.400629657781663
617 3.400176412011242
618 3.3997265662163607
619 3.3992800946668025
620 3.398836971828382
621 3.3983971723614115
622 3.3979606711191814
623 3.3975274431464504
624 3.3970974636779463
625 3.3966707081368908
626 3.3962471521335225
627 3.3958267714636476
628 3.3954095421071866
629 3.394995440226749
630 3.3945844421662095
631 3.3941765244492945
632 3.3937716637782005
633 3.393369837032194
634 3.3929710212662463
635 3.392575193709669
636 3.3921823317647646
637 3.3917924130054926
638 3.391405415176131
639 3.391021316189966
640 3.39064009412799
641 3.3902617272375983
642 3.3898861939313094
643 3.3895134727854894
644 3.3891435425390926
645 3.388776382092402
646 3.388411970505789
647 3.3880502869984865
648 3.387691310947356
649 3.3873350218856855
650 3.3869813995019773
651 3.3866304236387634
652 3.3862820742914175
653 3.3859363316069793
654 3.385593175882996
655 3.385252587566362
656 3.3849145472521798
657 3.3845790356826146
658 3.3842460337457787
659 3.3839155224745974
660 3.383587483045717
661 3.3832618967783934
662 3.3829387451334036
663 3.382618009711964
664 3.382299672254652
665 3.381983714640347
666 3.3816701188851646
667 3.381358867141419
668 3.3810499416965696
669 3.3807433249721965
670 3.380438999522978
671 3.380136948035668
672 3.379837153328093
673 3.3795395983481478
674 3.3792442661728104
675 3.3789511400071484
676 3.37866020318335
677 3.3783714391597504
678 3.3780848315198715
679 3.37780036397147
680 3.3775180203455886
681 3.377237784595617
682 3.376959640796363
683 3.3766835731431235
684 3.3764095659507745
685 3.3761376036528508
686 3.3758676708006563
687 3.375599752062353
688 3.3753338322220863
689 3.3750698961790913
690 3.3748079289468285
691 3.3745479156521054
692 3.3742898415342215
693 3.374033691944113
694 3.373779452343497
695 3.3735271083040432
696 3.373276645506527
697 3.373028049740004
698 3.37278130690099
699 3.3725364029926457
700 3.3722933241239628
701 3.3720520565089624
702 3.3718125864658965
703 3.3715749004164643
704 3.3713389848850155
705 3.3711048264977808
706 3.370872411982094
707 3.3706417281656282
708 3.3704127619756297
709 3.3701855004381707
710 3.3699599306773917
711 3.369736039914764
712 3.3695138154683475
713 3.3692932447520603
714 3.369074315274952
715 3.368857014640485
716 3.368641330545813
717 3.368427250781076
718 3.368214763228693
719 3.368003855862666
720 3.367794516747882
721 3.3675867340394268
722 3.3673804959819016
723 3.3671757909087465
724 3.366972607241562
725 3.366770933489446
726 3.3665707582483346
727 3.366372070200332
728 3.366174858113075
729 3.3659791108390698
730 3.365784817315058
731 3.3655919665613805
732 3.365400547681336
733 3.36521054986056
734 3.365021962366401
735 3.3648347745473
736 3.3646489758321767
737 3.364464555729821
738 3.3642815038282903
739 3.3640998097943067
740 3.363919463372663
741 3.363740454385636
742 3.36356277273239
743 3.363386408388405
744 3.363211351404897
745 3.3630375919082387
746 3.3628651200994026
747 3.362693926253387
748 3.362524000718657
749 3.362355333916594
750 3.3621879163409405
751 3.3620217385572526
752 3.3618567912023583
753 3.3616930649838186
754 3.36153055067939
755 3.361369239136498
756 3.3612091212717052
757 3.361050188070193
758 3.3608924305852397
759 3.360735839937707
760 3.36058040731553
761 3.3604261239732067
762 3.3602729812312977
763 3.360120970475927
764 3.3599700831582835
765 3.359820310794131
766 3.359671644963321
767 3.359524077309305
768 3.3593775995386586
769 3.3592322034206
770 3.359087880786516
771 3.3589446235294997
772 3.358802423603871
773 3.358661273024726
774 3.3585211638674735
775 3.3583820882673745
776 3.358244038419099
777 3.358107006576267
778 3.3579709850510095
779 3.357835966213528
780 3.3577019424916448
781 3.3575689063703837
782 3.357436850391522
783 3.3573057671531727
784 3.357175649309354
785 3.3570464895695653
786 3.356918280698373
787 3.3567910155149887
788 3.3566646868928633
789 3.3565392877592695
790 3.356414811094899
791 3.356291249933459
792 3.3561685973612714
793 3.356046846516874
794 3.355925990590631
795 3.355806022824329
796 3.3556869365108035
797 3.3555687249935464
798 3.3554513816663194
799 3.355334899972781
800 3.355219273406105
801 3.3551044955086105
802 3.3549905598713847
803 3.3548774601339244
804 3.3547651899837536
805 3.3546537431560806
806 3.354543113433422
807 3.354433294645253
808 3.3543242806676523
809 3.3542160654229485
810 3.354108642879369
811 3.354002007050694
812 3.3538961519959214
813 3.353791071818906
814 3.3536867606680416
815 3.3535832127359093
816 3.3534804222589516
817 3.3533783835171374
818 3.3532770908336365
819 3.353176538574491
820 3.3530767211482906
821 3.352977633005853
822 3.3528792686399047
823 3.352781622584763
824 3.3526846894160247
825 3.3525884637502528
826 3.352492940244663
827 3.352398113596824
828 3.352303978544349
829 3.352210529864591
830 3.352117762374347
831 3.3520256709295597
832 3.351934250425013
833 3.3518434957940544
834 3.3517534020082884
835 3.3516639640772996
836 3.3515751770483564
837 3.3514870360061324
838 3.3513995360724222
839 3.351312672405858
840 3.3512264402016374
841 3.3511408346912437
842 3.351055851142168
843 3.3509714848576455
844 3.350887731176381
845 3.3508045854722774
846 3.3507220431541795
847 3.3506400996655974
848 3.3505587504844616
849 3.3504779911228435
850 3.350397817126709
851 3.3503182240756657
852 3.350239207582698
853 3.3501607632939243
854 3.350082886888341
855 3.350005574077579
856 3.3499288206056503
857 3.349852622248711
858 3.3497769748148176
859 3.349701874143675
860 3.3496273161064165
861 3.34955329660535
862 3.3494798115737296
863 3.349406856975524
864 3.3493344288051765
865 3.3492625230873836
866 3.349191135876861
867 3.3491202632581207
868 3.3490499013452406
869 3.348980046281647
870 3.3489106942398905
871 3.3488418414214247
872 3.3487734840563905
873 3.3487056184033985
874 3.348638240749312
875 3.348571347409034
876 3.3485049347253018
877 3.3484389990684678
878 3.3483735368362955
879 3.3483085444537526
880 3.348244018372804
881 3.348179955072209
882 3.3481163510573184
883 3.3480532028598757
884 3.347990507037813
885 3.347928260175059
886 3.3478664588813376
887 3.3478050997919775
888 3.3477441795677145
889 3.347683694894505
890 3.3476236424833288
891 3.347564019070006
892 3.3475048214150047
893 3.347446046303263
894 3.3473876905439903
895 3.3473297509704993
896 3.347272224440011

In [ ]:
print(w0 , w1 , w2 , w3)

0.9880822932926271 0.05097359256109866 0.21452888896628564 0.008805129032625092

In [ ]:
mae = abs(y - Yh).mean()
print(mae)

1.3934678096981037

**Neural network using keras**

In [ ]:
#Step 1 - Data definition
X = df[['TV', 'radio' ,	'newspaper']]
y = df[['sales']]

In [ ]:
#Step 2 - build the nueral network model
from keras import models,layers

model = models.Sequential()

model.add(layers.Dense(1 , input_shape = (3,)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4 (16.00 B)

 Trainable params: 4 (16.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#Step 3 - compile the neural network model
from keras import optimizers
sgd = optimizers.SGD(learning_rate=1e-5)

model.compile(loss = 'mse', optimizer=sgd , metrics=['mae'])

In [ ]:
#Step 4 - Train your model
model.fit(X,y , epochs= 250)

Epoch 1/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.7280 - mae: 1.4634
Epoch 2/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.4206 - mae: 1.5812
Epoch 3/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0982 - mae: 1.5486
Epoch 4/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3737 - mae: 1.5817
Epoch 5/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8198 - mae: 1.4685
Epoch 6/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8965 - mae: 1.5003
Epoch 7/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7368 - mae: 1.4701
Epoch 8/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2238 - mae: 1.5487
Epoch 9/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1702 - mae: 1.5351
Epoch 10/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9319 - mae: 1.4716
Epoch 11/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1529 - mae: 1.5390
Epoch 12/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3498 - mae: 1.5720
Epoch 13/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4.3102 - mae: 1.5765
Epoch 14/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 4.2686 - mae: 1.5981
Epoch 15/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1849 - mae: 1.5774
Epoch 16/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3867 - mae: 1.6362
Epoch 17/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0582 - mae: 1.5185
Epoch 18/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9417 - mae: 1.5302
Epoch 19/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0996 - mae: 1.5072
Epoch 20/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3347 - mae: 1.5749
Epoch 21/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5081 - mae: 1.5898
Epoch 22/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3492 - mae: 1.6121
Epoch 23/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6946 - mae: 1.4825
Epoch 24/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0125 - mae: 1.4914
Epoch 25/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6019 - mae: 1.6500
Epoch 26/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.4607 - mae: 1.6367
Epoch 27/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.9018 - mae: 1.5048
Epoch 28/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0953 - mae: 1.5731
Epoch 29/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7882 - mae: 1.4572
Epoch 30/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6130 - mae: 1.6775
Epoch 31/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0493 - mae: 1.5488
Epoch 32/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2793 - mae: 1.5940
Epoch 33/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0873 - mae: 1.5370
Epoch 34/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2285 - mae: 1.5458
Epoch 35/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9847 - mae: 1.4865
Epoch 36/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8605 - mae: 1.4863
Epoch 37/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1105 - mae: 1.5568
Epoch 38/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.2168 - mae: 1.5435
Epoch 39/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3076 - mae: 1.5682
Epoch 40/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4483 - mae: 1.6477
Epoch 41/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.7328 - mae: 1.6472
Epoch 42/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9956 - mae: 1.5368
Epoch 43/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3463 - mae: 1.5904
Epoch 44/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2375 - mae: 1.5391
Epoch 45/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2384 - mae: 1.6164
Epoch 46/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7366 - mae: 1.4855
Epoch 47/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5166 - mae: 1.6110
Epoch 48/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0559 - mae: 1.4942
Epoch 49/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8482 - mae: 1.4832
Epoch 50/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7128 - mae: 1.4783
Epoch 51/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0806 - mae: 1.5734
Epoch 52/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3565 - mae: 1.6242
Epoch 53/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.5348 - mae: 1.6581
Epoch 54/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8708 - mae: 1.5215
Epoch 55/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3106 - mae: 1.5922
Epoch 56/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2073 - mae: 1.5623
Epoch 57/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2686 - mae: 1.5978
Epoch 58/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1298 - mae: 1.5993
Epoch 59/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1567 - mae: 1.5990
Epoch 60/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3059 - mae: 1.5947
Epoch 61/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8168 - mae: 1.4750
Epoch 62/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4808 - mae: 1.6285
Epoch 63/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9709 - mae: 1.5300
Epoch 64/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3711 - mae: 1.6408
Epoch 65/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3271 - mae: 1.5521
Epoch 66/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1521 - mae: 1.5887
Epoch 67/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1790 - mae: 1.5820
Epoch 68/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0364 - mae: 1.5567
Epoch 69/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4813 - mae: 1.6395
Epoch 70/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4313 - mae: 1.6388
Epoch 71/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1200 - mae: 1.5671
Epoch 72/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1928 - mae: 1.5673
Epoch 73/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5486 - mae: 1.4293
Epoch 74/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1849 - mae: 1.5761
Epoch 75/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9870 - mae: 1.4956
Epoch 76/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1497 - mae: 1.5456
Epoch 77/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4557 - mae: 1.6564
Epoch 78/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5109 - mae: 1.6176
Epoch 79/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8915 - mae: 1.4928
Epoch 80/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2825 - mae: 1.5671
Epoch 81/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2965 - mae: 1.5535
Epoch 82/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9843 - mae: 1.5322
Epoch 83/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2099 - mae: 1.5740
Epoch 84/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7667 - mae: 1.5124
Epoch 85/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4619 - mae: 1.5494
Epoch 86/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7721 - mae: 1.4859
Epoch 87/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.1459 - mae: 1.5494
Epoch 88/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0229 - mae: 1.5399
Epoch 89/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9321 - mae: 1.4738
Epoch 90/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1549 - mae: 1.5900
Epoch 91/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2995 - mae: 1.5816
Epoch 92/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7361 - mae: 1.4673
Epoch 93/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9796 - mae: 1.5352
Epoch 94/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3128 - mae: 1.5723
Epoch 95/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0149 - mae: 1.5409
Epoch 96/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8123 - mae: 1.4869
Epoch 97/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1217 - mae: 1.5491
Epoch 98/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4822 - mae: 1.6355
Epoch 99/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1310 - mae: 1.5696
Epoch 100/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0496 - mae: 1.5422
Epoch 101/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7798 - mae: 1.4890
Epoch 102/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7987 - mae: 1.4812
Epoch 103/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0109 - mae: 1.5552
Epoch 104/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8591 - mae: 1.5136
Epoch 105/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7637 - mae: 1.4870
Epoch 106/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2850 - mae: 1.5624
Epoch 107/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4576 - mae: 1.6346
Epoch 108/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1468 - mae: 1.5897
Epoch 109/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0339 - mae: 1.4885
Epoch 110/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4472 - mae: 1.6207
Epoch 111/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8950 - mae: 1.5171
Epoch 112/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.3661 - mae: 1.5985
Epoch 113/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.8306 - mae: 1.5021
Epoch 114/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.5791 - mae: 1.4763
Epoch 115/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.1229 - mae: 1.4918
Epoch 116/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.0670 - mae: 1.5558
Epoch 117/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.5892 - mae: 1.6418
Epoch 118/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0260 - mae: 1.5447
Epoch 119/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.2055 - mae: 1.6088
Epoch 120/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.3242 - mae: 1.6421
Epoch 121/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0546 - mae: 1.5035
Epoch 122/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.9083 - mae: 1.5751
Epoch 123/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.3825 - mae: 1.6233
Epoch 124/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.0193 - mae: 1.5379
Epoch 125/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.5876 - mae: 1.4550
Epoch 126/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.8841 - mae: 1.5405
Epoch 127/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.4547 - mae: 1.5987
Epoch 128/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.2960 - mae: 1.5593
Epoch 129/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.9092 - mae: 1.5030
Epoch 130/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.4136 - mae: 1.6305
Epoch 131/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8934 - mae: 1.5281
Epoch 132/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1644 - mae: 1.5914
Epoch 133/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0089 - mae: 1.5333
Epoch 134/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0139 - mae: 1.5379
Epoch 135/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3954 - mae: 1.6419
Epoch 136/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7917 - mae: 1.5170
Epoch 137/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1433 - mae: 1.5752
Epoch 138/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0236 - mae: 1.5275
Epoch 139/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.9715 - mae: 1.5487
Epoch 140/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1361 - mae: 1.5513
Epoch 141/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6646 - mae: 1.7026
Epoch 142/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0531 - mae: 1.5235
Epoch 143/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1892 - mae: 1.5667
Epoch 144/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5483 - mae: 1.4323
Epoch 145/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1815 - mae: 1.6240
Epoch 146/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2489 - mae: 1.5952
Epoch 147/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2832 - mae: 1.6140
Epoch 148/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1935 - mae: 1.5624
Epoch 149/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7851 - mae: 1.4923
Epoch 150/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0670 - mae: 1.5520
Epoch 151/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0872 - mae: 1.5264
Epoch 152/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0231 - mae: 1.5374
Epoch 153/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7745 - mae: 1.5071
Epoch 154/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5525 - mae: 1.4669
Epoch 155/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.6141 - mae: 1.4788
Epoch 156/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8994 - mae: 1.5002
Epoch 157/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.7413 - mae: 1.4590
Epoch 158/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1465 - mae: 1.5829
Epoch 159/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8148 - mae: 1.4997
Epoch 160/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9660 - mae: 1.5075
Epoch 161/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2312 - mae: 1.5430
Epoch 162/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8428 - mae: 1.4945
Epoch 163/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9538 - mae: 1.5300
Epoch 164/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7420 - mae: 1.4934
Epoch 165/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7449 - mae: 1.4920
Epoch 166/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3328 - mae: 1.6512
Epoch 167/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2682 - mae: 1.6275
Epoch 168/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9497 - mae: 1.5470
Epoch 169/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6363 - mae: 1.4705
Epoch 170/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3674 - mae: 1.6243
Epoch 171/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3400 - mae: 1.5961
Epoch 172/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5232 - mae: 1.5748
Epoch 173/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.1631 - mae: 1.5931
Epoch 174/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0819 - mae: 1.5436
Epoch 175/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1856 - mae: 1.5898
Epoch 176/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1240 - mae: 1.5347
Epoch 177/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5218 - mae: 1.6510
Epoch 178/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6754 - mae: 1.4375
Epoch 179/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.9270 - mae: 1.6951
Epoch 180/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6631 - mae: 1.4399
Epoch 181/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.8094 - mae: 1.4835
Epoch 182/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6572 - mae: 1.4732
Epoch 183/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0342 - mae: 1.5257
Epoch 184/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0654 - mae: 1.5924
Epoch 185/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1688 - mae: 1.5729
Epoch 186/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0349 - mae: 1.5495
Epoch 187/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3945 - mae: 1.5959
Epoch 188/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1835 - mae: 1.5684
Epoch 189/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2964 - mae: 1.5632
Epoch 190/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9242 - mae: 1.5697
Epoch 191/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5128 - mae: 1.6456
Epoch 192/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0055 - mae: 1.5137
Epoch 193/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3597 - mae: 1.5763
Epoch 194/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1177 - mae: 1.5541
Epoch 195/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2034 - mae: 1.5718
Epoch 196/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1373 - mae: 1.5394
Epoch 197/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0987 - mae: 1.5072
Epoch 198/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6845 - mae: 1.4843
Epoch 199/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0878 - mae: 1.5564
Epoch 200/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2548 - mae: 1.5698
Epoch 201/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9250 - mae: 1.5010
Epoch 202/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9972 - mae: 1.5350
Epoch 203/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2446 - mae: 1.5871
Epoch 204/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1692 - mae: 1.5612
Epoch 205/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8768 - mae: 1.4940
Epoch 206/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0601 - mae: 1.5095
Epoch 207/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4888 - mae: 1.6077
Epoch 208/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1340 - mae: 1.5055
Epoch 209/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9387 - mae: 1.5466
Epoch 210/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2349 - mae: 1.5716
Epoch 211/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.0642 - mae: 1.5092
Epoch 212/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.1046 - mae: 1.5178
Epoch 213/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6554 - mae: 1.4638
Epoch 214/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8899 - mae: 1.5247
Epoch 215/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0740 - mae: 1.5972
Epoch 216/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0193 - mae: 1.5469
Epoch 217/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9486 - mae: 1.4824
Epoch 218/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8280 - mae: 1.5305
Epoch 219/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4799 - mae: 1.5961
Epoch 220/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6399 - mae: 1.4613
Epoch 221/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6772 - mae: 1.4896
Epoch 222/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0140 - mae: 1.5148
Epoch 223/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4487 - mae: 1.6508
Epoch 224/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1508 - mae: 1.5363
Epoch 225/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2826 - mae: 1.6124
Epoch 226/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4278 - mae: 1.5696
Epoch 227/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7112 - mae: 1.4878
Epoch 228/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8453 - mae: 1.4942
Epoch 229/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9648 - mae: 1.5529
Epoch 230/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.8701 - mae: 1.5007
Epoch 231/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8801 - mae: 1.4819
Epoch 232/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7416 - mae: 1.5054
Epoch 233/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9571 - mae: 1.4771
Epoch 234/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6156 - mae: 1.4622
Epoch 235/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9668 - mae: 1.5733
Epoch 236/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5418 - mae: 1.6525
Epoch 237/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2787 - mae: 1.5703
Epoch 238/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7871 - mae: 1.4978
Epoch 239/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0994 - mae: 1.5389
Epoch 240/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4318 - mae: 1.6402
Epoch 241/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0704 - mae: 1.5207
Epoch 242/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.7685 - mae: 1.4692
Epoch 243/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3135 - mae: 1.6085
Epoch 244/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2910 - mae: 1.6012
Epoch 245/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1469 - mae: 1.6171
Epoch 246/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5594 - mae: 1.6480
Epoch 247/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.1360 - mae: 1.5388
Epoch 248/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.8153 - mae: 1.6931
Epoch 249/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.7871 - mae: 1.4840
Epoch 250/250
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7522 - mae: 1.4736

In [ ]:
Yp = model.predict(X)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

In [ ]:
abs(y - Yp).mean()

sales    1.560925
dtype: float64

**Deep neural network**

 - add hidden layers

In [ ]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,y)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(xtrain)

xtrainScaled = scaler.transform(xtrain)
xtestScaled = scaler.transform(xtest)

In [ ]:
xtrainScaled.shape

(150, 3)

In [ ]:
#Step 2 - build the nueral network model
from keras import models,layers

modelB = models.Sequential()

modelB.add(layers.Dense(2 , activation='relu' , input_shape = (3,)))

modelB.add(layers.Dense(1 , activation='relu'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
modelB.summary()

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_28 (Dense)                │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11 (44.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
sgd = optimizers.SGD(learning_rate=1e-2)
modelB.compile(loss = 'mse', optimizer=sgd , metrics=['mae'])

In [ ]:
modelB.fit(xtrainScaled,ytrain , epochs=100, validation_data=(xtestScaled,ytest))

Epoch 1/100
4/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 179.9454 - mae: 12.6309

/usr/local/lib/python3.11/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 173.2897 - mae: 12.3147 - val_loss: 39.4187 - val_mae: 5.1942
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 24.2200 - mae: 4.0585 - val_loss: 12.5003 - val_mae: 2.6080
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 9.7751 - mae: 2.3661 - val_loss: 11.8625 - val_mae: 2.5808
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 6.7884 - mae: 2.0479 - val_loss: 10.6097 - val_mae: 2.3557
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 6.4146 - mae: 1.9145 - val_loss: 10.1596 - val_mae: 2.3553
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 6.3253 - mae: 1.8394 - val_loss: 9.6034 - val_mae: 2.2959
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5.2094 - mae: 1.6939 - val_loss: 8.4641 - val_mae: 2.0737
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 4.1549 - mae: 1.4916 - val_loss: 7.9110 - val_mae: 1.9997
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 4.1180 - mae: 1.5272 - val_loss: 7.3897 - val_mae: 1.9161
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 4.1826 - mae: 1.4276 - val_loss: 7.3347 - val_mae: 1.9512
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 4.9230 - mae: 1.5755 - val_loss: 6.7145 - val_mae: 1.8446
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 3.5768 - mae: 1.3726 - val_loss: 6.6004 - val_mae: 1.8303
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 3.1496 - mae: 1.3012 - val_loss: 6.1705 - val_mae: 1.7569
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 4.2299 - mae: 1.4283 - val_loss: 5.9716 - val_mae: 1.7262
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.5483 - mae: 1.1747 - val_loss: 5.5880 - val_mae: 1.6990
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 3.1326 - mae: 1.3455 - val_loss: 5.7013 - val_mae: 1.6789
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.8937 - mae: 1.1846 - val_loss: 5.3092 - val_mae: 1.6260
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.6389 - mae: 1.2108 - val_loss: 5.1444 - val_mae: 1.6178
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.3335 - mae: 1.2011 - val_loss: 5.3005 - val_mae: 1.6123
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.4774 - mae: 1.1716 - val_loss: 5.1271 - val_mae: 1.5983
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.4087 - mae: 1.0725 - val_loss: 4.8768 - val_mae: 1.6174
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.3347 - mae: 1.1814 - val_loss: 5.0155 - val_mae: 1.5843
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.7069 - mae: 1.2150 - val_loss: 4.8819 - val_mae: 1.5809
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.1106 - mae: 1.0761 - val_loss: 4.7476 - val_mae: 1.6008
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.7369 - mae: 1.2840 - val_loss: 4.8222 - val_mae: 1.5724
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2.3156 - mae: 1.1947 - val_loss: 4.6888 - val_mae: 1.5970
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.0279 - mae: 1.0963 - val_loss: 4.6618 - val_mae: 1.6017
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2.1815 - mae: 1.1480 - val_loss: 4.6673 - val_mae: 1.5872
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.9214 - mae: 1.0691 - val_loss: 4.7139 - val_mae: 1.5685
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.2053 - mae: 1.1175 - val_loss: 4.9082 - val_mae: 1.5555
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.1649 - mae: 1.0689 - val_loss: 4.7601 - val_mae: 1.5585
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 1.8566 - mae: 1.0356 - val_loss: 5.0069 - val_mae: 1.5641
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - loss: 2.1323 - mae: 1.1007 - val_loss: 4.7293 - val_mae: 1.5575
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 92ms/step - loss: 2.1927 - mae: 1.1085 - val_loss: 5.0465 - val_mae: 1.5719
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 2.7823 - mae: 1.2568 - val_loss: 4.6388 - val_mae: 1.5708
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2661 - mae: 1.1589 - val_loss: 4.6743 - val_mae: 1.5621
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2569 - mae: 1.1489 - val_loss: 4.6327 - val_mae: 1.5715
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2401 - mae: 1.1374 - val_loss: 4.9347 - val_mae: 1.5525
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.0465 - mae: 1.1095 - val_loss: 4.5894 - val_mae: 1.6068
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.0815 - mae: 1.1193 - val_loss: 4.7030 - val_mae: 1.5552
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.2679 - mae: 1.1888 - val_loss: 4.8271 - val_mae: 1.5441
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.9256 - mae: 1.0438 - val_loss: 4.6503 - val_mae: 1.5605
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.9002 - mae: 1.0591 - val_loss: 4.7134 - val_mae: 1.5494
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.1506 - mae: 1.1484 - val_loss: 4.7754 - val_mae: 1.5428
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.1862 - mae: 1.1370 - val_loss: 4.9631 - val_mae: 1.5562
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.3426 - mae: 1.1486 - val_loss: 4.9060 - val_mae: 1.5471
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.1665 - mae: 1.1207 - val_loss: 4.8769 - val_mae: 1.5444
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 1.9654 - mae: 1.0627 - val_loss: 4.6393 - val_mae: 1.5665
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.2574 - mae: 1.1740 - val_loss: 4.9715 - val_mae: 1.5591
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2134 - mae: 1.1312 - val_loss: 4.6230 - val_mae: 1.6751
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.1120 - mae: 1.1238 - val_loss: 4.6590 - val_mae: 1.5621
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.2982 - mae: 1.1806 - val_loss: 4.9959 - val_mae: 1.5652
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.4099 - mae: 1.1663 - val_loss: 5.0676 - val_mae: 1.5772
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.7463 - mae: 1.2453 - val_loss: 4.6983 - val_mae: 1.5538
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.2565 - mae: 1.1585 - val_loss: 4.6078 - val_mae: 1.6029
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 2.2266 - mae: 1.1813 - val_loss: 4.8113 - val_mae: 1.5397
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.2137 - mae: 1.1589 - val_loss: 4.6332 - val_mae: 1.5750
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2061 - mae: 1.1365 - val_loss: 4.8601 - val_mae: 1.5418
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2348 - mae: 1.1512 - val_loss: 4.7905 - val_mae: 1.5410
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.3029 - mae: 1.1821 - val_loss: 4.7900 - val_mae: 1.5411
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.5465 - mae: 1.2613 - val_loss: 5.0725 - val_mae: 1.5785
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.8405 - mae: 1.0310 - val_loss: 4.9830 - val_mae: 1.5640
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1.8744 - mae: 1.0331 - val_loss: 4.6105 - val_mae: 1.6183
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.1469 - mae: 1.1395 - val_loss: 4.6141 - val_mae: 1.5996
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.9816 - mae: 1.0879 - val_loss: 4.6204 - val_mae: 1.5886
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.0724 - mae: 1.1220 - val_loss: 4.6159 - val_mae: 1.5938
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.1076 - mae: 1.1177 - val_loss: 4.6334 - val_mae: 1.5768
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.1943 - mae: 1.1432 - val_loss: 4.9156 - val_mae: 1.5572
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.2596 - mae: 1.1382 - val_loss: 4.8412 - val_mae: 1.5449
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2.1075 - mae: 1.1080 - val_loss: 4.6770 - val_mae: 1.5541
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 1.9835 - mae: 1.0976 - val_loss: 4.7314 - val_mae: 1.5447
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - loss: 2.5017 - mae: 1.2179 - val_loss: 4.6797 - val_mae: 1.5529
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 84ms/step - loss: 1.9390 - mae: 1.0651 - val_loss: 4.9529 - val_mae: 1.5592
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - loss: 2.4047 - mae: 1.1865 - val_loss: 4.7779 - val_mae: 1.5394
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.2633 - mae: 1.1694 - val_loss: 4.8504 - val_mae: 1.5433
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.1305 - mae: 1.1219 - val_loss: 4.6835 - val_mae: 1.5492
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.0172 - mae: 1.0868 - val_loss: 4.7527 - val_mae: 1.5411
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.1040 - mae: 1.1095 - val_loss: 4.7888 - val_mae: 1.5398
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.0904 - mae: 1.1044 - val_loss: 4.7174 - val_mae: 1.5442
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.0965 - mae: 1.1309 - val_loss: 4.6028 - val_mae: 1.5949
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.1051 - mae: 1.1387 - val_loss: 4.7224 - val_mae: 1.5423
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.0838 - mae: 1.1127 - val_loss: 4.9310 - val_mae: 1.5542
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 1.8846 - mae: 1.0657 - val_loss: 4.5988 - val_mae: 1.6405
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.2358 - mae: 1.1941 - val_loss: 4.7392 - val_mae: 1.5400
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.1777 - mae: 1.1520 - val_loss: 4.7126 - val_mae: 1.5422
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.2932 - mae: 1.1527 - val_loss: 4.7089 - val_mae: 1.5402
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 1.8874 - mae: 1.0781 - val_loss: 4.6369 - val_mae: 1.5556
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2.3962 - mae: 1.2051 - val_loss: 4.6721 - val_mae: 1.5445
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.2083 - mae: 1.1670 - val_loss: 4.5768 - val_mae: 1.6139
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.0574 - mae: 1.1000 - val_loss: 4.6300 - val_mae: 1.5555
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.1309 - mae: 1.1229 - val_loss: 4.6704 - val_mae: 1.5431
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.0374 - mae: 1.1011 - val_loss: 4.6132 - val_mae: 1.5635
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.1874 - mae: 1.1757 - val_loss: 4.9531 - val_mae: 1.5612
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2.2343 - mae: 1.1426 - val_loss: 4.7591 - val_mae: 1.5323
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.0132 - mae: 1.0898 - val_loss: 4.7180 - val_mae: 1.5337
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.3866 - mae: 1.2321 - val_loss: 4.7743 - val_mae: 1.5312
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.2172 - mae: 1.1347 - val_loss: 5.1246 - val_mae: 1.5896
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 1.8919 - mae: 1.0335 - val_loss: 4.6145 - val_mae: 1.5558
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.2354 - mae: 1.1840 - val_loss: 4.6617 - val_mae: 1.5394
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.1739 - mae: 1.1666 - val_loss: 4.6324 - val_mae: 1.5461

In [ ]:
modelB.evaluate(xtrainScaled,ytrain)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.0060 - mae: 1.1327

/usr/local/lib/python3.11/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(

[2.078747510910034, 1.1224819421768188]

In [ ]:
modelB.evaluate(xtestScaled,ytest)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 4.8921 - mae: 1.5682

/usr/local/lib/python3.11/dist-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(

[4.632429599761963, 1.5461291074752808]