In [ ]:
dataset = [['Milk' , 'Onion' , 'Nutmeg' , 'Kidney Beans' , 'Eggs' , 'Yogurt'],
           ['Dill' , 'Onion' , 'Nutmeg' , 'Kidney Beans' , 'Eggs' , 'Yogurt'],
           ['Milk' , 'Apple' , 'Kidney Beans' , 'Eggs'],
           ['Milk' , 'Unicorn' , 'Corn' , 'Kidney Beans' , 'Yogurt'],
           ['Corn' , 'Onion' , 'Onion' , 'Kidney Beans' , 'Ice cream' , 'Eggs']]

print(dataset)

[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Milk', 'Apple', 'Kidney Beans', 'Eggs'], ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'], ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
te = TransactionEncoder()
te.fit(dataset)
te.columns_

['Apple',
 'Corn',
 'Dill',
 'Eggs',
 'Ice cream',
 'Kidney Beans',
 'Milk',
 'Nutmeg',
 'Onion',
 'Unicorn',
 'Yogurt']

In [ ]:
df = pd.DataFrame(te.transform(dataset) , columns = te.columns_)
df

   Apple   Corn   Dill   Eggs  Ice cream  ...   Milk  Nutmeg  Onion  Unicorn  Yogurt
0  False  False  False   True      False  ...   True    True   True    False    True
1  False  False   True   True      False  ...  False    True   True    False    True
2   True  False  False   True      False  ...   True   False  False    False   False
3  False   True  False  False      False  ...   True   False  False     True    True
4  False   True  False   True       True  ...  False   False   True    False   False

[5 rows x 11 columns]

In [ ]:
from mlxtend.frequent_patterns import apriori
frequent_items = apriori(df, use_colnames=True, min_support=0.5)
frequent_items

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Kidney Beans, Eggs)
6       0.6                (Onion, Eggs)
7       0.6         (Kidney Beans, Milk)
8       0.6        (Kidney Beans, Onion)
9       0.6       (Kidney Beans, Yogurt)
10      0.6  (Kidney Beans, Onion, Eggs)

In [ ]:
from mlxtend.frequent_patterns import association_rules
res = association_rules(frequent_items,metric='confidence',min_threshold=0.6)
res

/usr/local/lib/python3.11/dist-packages/mlxtend/frequent_patterns/association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

              antecedents            consequents  ...  certainty  kulczynski
0          (Kidney Beans)                 (Eggs)  ...      0.000       0.900
1                  (Eggs)         (Kidney Beans)  ...      0.000       0.900
2                 (Onion)                 (Eggs)  ...      1.000       0.875
3                  (Eggs)                (Onion)  ...      0.375       0.875
4          (Kidney Beans)                 (Milk)  ...      0.000       0.800
5                  (Milk)         (Kidney Beans)  ...      0.000       0.800
6          (Kidney Beans)                (Onion)  ...      0.000       0.800
7                 (Onion)         (Kidney Beans)  ...      0.000       0.800
8          (Kidney Beans)               (Yogurt)  ...      0.000       0.800
9                (Yogurt)         (Kidney Beans)  ...      0.000       0.800
10  (Kidney Beans, Onion)                 (Eggs)  ...      1.000       0.875
11   (Kidney Beans, Eggs)                (Onion)  ...      0.375       0.875
12          (Onion, Eggs)         (Kidney Beans)  ...      0.000       0.800
13         (Kidney Beans)          (Onion, Eggs)  ...      0.000       0.800
14                (Onion)   (Kidney Beans, Eggs)  ...      1.000       0.875
15                 (Eggs)  (Kidney Beans, Onion)  ...      0.375       0.875

[16 rows x 14 columns]

In [ ]:
res1 = res[['antecedents','consequents','support','confidence','lift']]
res1

              antecedents            consequents  support  confidence  lift
0          (Kidney Beans)                 (Eggs)      0.8        0.80  1.00
1                  (Eggs)         (Kidney Beans)      0.8        1.00  1.00
2                 (Onion)                 (Eggs)      0.6        1.00  1.25
3                  (Eggs)                (Onion)      0.6        0.75  1.25
4          (Kidney Beans)                 (Milk)      0.6        0.60  1.00
5                  (Milk)         (Kidney Beans)      0.6        1.00  1.00
6          (Kidney Beans)                (Onion)      0.6        0.60  1.00
7                 (Onion)         (Kidney Beans)      0.6        1.00  1.00
8          (Kidney Beans)               (Yogurt)      0.6        0.60  1.00
9                (Yogurt)         (Kidney Beans)      0.6        1.00  1.00
10  (Kidney Beans, Onion)                 (Eggs)      0.6        1.00  1.25
11   (Kidney Beans, Eggs)                (Onion)      0.6        0.75  1.25
12          (Onion, Eggs)         (Kidney Beans)      0.6        1.00  1.00
13         (Kidney Beans)          (Onion, Eggs)      0.6        0.60  1.00
14                (Onion)   (Kidney Beans, Eggs)      0.6        1.00  1.25
15                 (Eggs)  (Kidney Beans, Onion)      0.6        0.75  1.25